name: Update Swift Package
on:
  # Allow a manual trigger of the update process.
  workflow_dispatch:
  schedule:
  # Check for updates every hour during the week (we don't release on weekends).
  - cron: '0 * * * 1-5'

jobs:
  version-update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # We want to fetch all of the tags for our check.
        fetch-depth: 0
    - name: Check and Update Package Version
      run: ./.github/scripts/version-update.sh
      shell: bash